### ISSUE TITLE
无法构建

### ISSUE THREAD

**Issue by zjbdiy** [122006/Zircon#2]
很奇怪这里为什么没有issue?

android studio 2020.3.1
jdk 1.8
最新2.3版本
已安装插件
安卓项目
> Task :app:compileDebugJavaWithJavac FAILED
inject [动态字符串插件]
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.10, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.IllegalAccessError: class com.sun.tools.javac.parser.ZrJavaTokenizer (in module jdk.compiler) cannot access class formatter.Formatter (in unnamed module @0x67a75210) because module jdk.compiler does not read unnamed module @0x67a75210
	at jdk.compiler/com.sun.tools.javac.parser.ZrJavaTokenizer.handler(ZrJavaTokenizer.java:78)
	at jdk.compiler/com.sun.tools.javac.parser.ZrJavaTokenizer.readToken(ZrJavaTokenizer.java:31)
	at jdk.compiler/com.sun.tools.javac.parser.Scanner.nextToken(Scanner.java:115)
	at jdk.compiler/com.sun.tools.javac.parser.JavacParser.nextToken(JavacParser.java:245)
很抱歉  我不知道提供哪些信息有帮助,我无法判断是插件错误还是环境错误 总之无法编译

**Comment by 122006** [comment]
很抱歉带来不便，如果没有特殊要求，请修改gradle jvm版本为java8
修改gradle版本位置：File | Settings | Build, Execution, Deployment | Build Tools | Gradle

为了减少的处理速度，该项目没有使用jsr-269相关方案，所以在java9以上的编译jvm中会导致module错误
在未来版本会提供两者的可选性配置
对您的安卓代码生成不会有任何影响

**Comment by zjbdiy** [comment]
这...  很客气  回答很详细了  但是我留下了没有技术的泪水
我修改了版本之后 gradle文件报错了  
报错信息
Build file 'D:\vs\ZStock\ZStock\app\build.gradle' line: 23

A problem occurred evaluating project ':app'.
> Could not find method android() for arguments [build_bk4zvfxo9965jyrw32wnq303a$_run_closure1@5c063af8] on project ':app' of type org.gradle.api.Project.

gradle
plugins {
   // id 'com.android.application'
}

// 读取版本号
def getVersionCode() {
    def versionFile = file('version.properties')
    if (versionFile.canRead()){
        Properties versionProps = new Properties()
        versionProps.load(new FileInputStream(versionFile))
        def versionCode = versionProps['VERSION_CODE'].toInteger()
        def runTasks = gradle.startParameter.taskNames
        if (runTasks.toString().contains('assembleRelease')) {
            versionProps['VERSION_CODE'] = (++versionCode).toString()
            versionProps.store(versionFile.newWriter(), null)
        }
        return versionCode
    } else {
        throw new GradleException("Could not find version.properties!")
    }
}

android {

    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    def currentVersionCode = getVersionCode()

    viewBinding{
        enabled=true
    }

    tasks.withType(JavaCompile) {
        options.compilerArgs  << "-Xplugin:ZrString"
    }

    defaultConfig {
        applicationId "com.zjbdiy.zstock"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode currentVersionCode
        versionName "1.0"

我没有实力解决这个问题  很惭愧   感谢您的恢复

**Comment by 122006** [comment]
:)，工单式回答习惯了~
请不要注释// id 'com.android.application'，会导致编译器无法成功构建android项目。

**Comment by zjbdiy** [comment]
历经千辛万苦(走弯路)之后,成功用上了
最开始改变版本之后  // id 'com.android.application 这句报错了  所以注释掉以为会好,结果更糟了  经过您的提醒 这句比必须的
我考虑到可能gradle的版本太新了   我仔细看了文档  gradle从4.2以后就直接变成7了 7需要java11才能运行 我将其改成4.2.2就可以编译了
总之非常感谢您的耐心及分享精神,不但用上了 还学到了相关的知识
