### ISSUE TITLE
运行报错,缺少分号

### ISSUE THREAD

**Issue by lianlianyi** [122006/Zircon#3]
idea 插件有安装 ,但是运行一直缺少; 是否跟jdk版本有关系呢?

![image](https://user-images.githubusercontent.com/1701810/155866846-23adcd1f-33e4-4ce3-b35d-3ea7c42d95fb.png)

![image](https://user-images.githubusercontent.com/1701810/155866837-ea6731f7-ad9d-4e52-a99a-c49933a57b7a.png)

**Comment by 122006** [comment]
需要引入依赖
 ```
<dependency>
        <groupId>com.github.122006.Zircon</groupId>
        <artifactId>javac</artifactId>
        <version>2.6</version>
 </dependency>
<dependency>
        <groupId>com.github.122006.Zircon</groupId>
        <artifactId>base</artifactId>
        <version>2.6</version>
 </dependency>
```

**Comment by lianlianyi** [comment]
我用的是jdk17,已经加入这两个依赖了..还是不行

**Comment by 122006** [comment]
目前只测试可用性到jdk11。近期会测试一下在更高版本jdk中的问题。
如果想要尝试本项目，烦请调整java编译版本为jdk11及以下

**Comment by lianlianyi** [comment]
太感谢了..期待有jdk17的支持

**Comment by lianlianyi** [comment]
请问jdk17版本的是否有进展呢..
尝试加了idea的jvm跟maven的编译参数,但还是失败了
                        <arg>-Xlint:all</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED</arg>

**Comment by 122006** [comment]
高版本jdk中javac的JavaTokenizer结构改动比较大，我来适配一下

**Comment by 122006** [comment]
jdk17的问题我在gradle里测试稳定了，对maven不太熟悉麻烦试试
<dependency>
            <groupId>com.github.122006.Zircon</groupId>
            <artifactId>javac</artifactId>
            <version>a510a6ea6a</version>
</dependency>

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <fork>true</fork>
                    <source>17</source>
                    <target>17</target>
                    <showWarnings>true</showWarnings>
                    <encoding>UTF8</encoding>
                    <compilerVersion>17</compilerVersion>
                    <compilerArgs>
                        <arg>-Xplugin:ZrString</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                    </compilerArgs>
                </configuration>
            </plugin>


如果直接运行报错，可以试试package能不能成功
感谢~

**Comment by lianlianyi** [comment]
感谢,已经升级到2.7版本了,目前jdk17还是提示插件不可用,是有有可能是idea插件版本太低,我想下载https://github.com/122006/Zircon/blob/master/ijplugin/build/distributions/ijplugin-1.9.zip ,该url链接失效

**Comment by 122006** [comment]
maven我不太熟，还在看配置怎么配置，gradle已经支持jdk17了，理论上maven里参数对了是可以正常使用的
和idea插件版本无关，idea插件只是为了代码不标红，即使没有安装插件，代码也可以正常运行的。idea插件我已经传上来了

**Comment by 122006** [comment]
请尝试以下配置
````<build>
        <plugins>
            ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <fork>true</fork>
                    <source>17</source>
                    <target>17</target>
                    <showWarnings>true</showWarnings>
                    <encoding>UTF8</encoding>
                    <compilerVersion>17</compilerVersion>
                    <executable>你的jdk路径,如果当前默认已经是java17，可以去掉</executable>
                    <goal>exec</goal>
                    <compilerArgs>
                        <arg>-Xplugin:ZrString</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>````

**Comment by lianlianyi** [comment]
maven 还是不行 ,你用的是oraclejdk17吗?
[WARNING] jdk:17.0.1
java.lang.RuntimeException: 找不到对应类:com.sun.tools.javac.parser.Item
	at com.by122006.zircon.ZirconStringPlugin.reloadClass(ZirconStringPlugin.java:141)
	at com.by122006.zircon.ZirconStringPlugin.reloadClass(ZirconStringPlugin.java:123)
	at com.by122006.zircon.ZirconStringPlugin.startTask(ZirconStringPlugin.java:68)
	at com.by122006.zircon.ZirconStringPlugin.access$000(ZirconStringPlugin.java:21)
	at com.by122006.zircon.ZirconStringPlugin$1.started(ZirconStringPlugin.java:42)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.started(ClientCodeWrapper.java:843)
	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.started(MultiTaskListener.java:119)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:614)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:657)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:1006)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:993)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:919)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)

**Comment by 122006** [comment]
增加一个依赖
<dependency>
       <groupId>com.github.122006.Zircon</groupId>
       <artifactId>base</artifactId>
       <version>2.7</version>
</dependency>

**Comment by lianlianyi** [comment]
感谢大佬,,可以了,不知道是否我的问题, 再补充这句 <arg>-J--add-opens=java.base/java.lang=ALL-UNNAMED</arg>
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <fork>true</fork>
                    <source>17</source>
                    <target>17</target>
                    <showWarnings>true</showWarnings>
                    <encoding>UTF8</encoding>
                    <compilerVersion>17</compilerVersion>
                    
                    <goal>exec</goal>
                    <compilerArgs>
                        <arg>-Xplugin:ZrString</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
                        <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=java.base/java.lang=ALL-UNNAMED</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

**Comment by lianlianyi** [comment]
感谢大佬,已经可以使用了,插件再补充这句
 <arg>-J--add-opens=java.base/java.lang=ALL-UNNAMED</arg>
