### ISSUE TITLE
使用模板字符串中, 在 ${} 中 new 一个对象, 会显示类的全路径名称

### ISSUE THREAD

**Issue by springandme** [122006/Zircon#5]

**Comment by springandme** [comment]
IDEA 2020.3.4
JDK jdk15.0.2
Zircon  2.3

![question](https://user-images.githubusercontent.com/44739137/183341433-5a3274bb-b72b-4f9a-8749-c05ecf9eab2c.gif)

**Comment by 122006** [comment]
本质上内插内容是一段java fragment。这个问题是由于自动补全的时候，在import中没有找到对应的类，只能使用全限定类名进行补全。
在真实代码环境中，这个是很少见的情况，因为大多数时候已经在上下文中被导入，就算全限定类名导入，也因为插件的折叠效果不影响美观。
如果让你感到困惑，可以外部代码import后再进行内插内容的编写；或者复杂内接内容可以使用进行'+'书写，然后使用alt+enter选择zircon的操作进行转换。
![image](https://user-images.githubusercontent.com/16866618/183346477-6b269fda-5fbb-4017-8694-2869683783e1.png)
你提出问题的兼容方案会在未来的版本中进行考虑
此外，注意到你使用了较旧版本(2.3)的插件，旧版本会在某些功能上存在缺陷，可以尝试下最新版本哦

**Comment by springandme** [comment]
好的, 感谢作者的回复, 刚才试了试你那种方案可以转换, 这个 Zircon 版本取决于 IDEA 的版本, 所有我现在没法更新最新版本, 有机会肯定试一试最新版本
