### ISSUE TITLE
Zicon 插件配合 Idea 的格式化代码功能, 字符串总是与「圆括号 ()」之间存在一个空格

### ISSUE THREAD

**Issue by springandme** [122006/Zircon#6]
OS   win10
Idea 2022.2.2
Zicron 插件 2.8
JDK 8 | 15

Idea 自带的格式化快捷键 Ctrl + Atl + L, 新版 Idea 自带功能Ctrl + S 保存触发格式化和 Save Actions 插件保存触发格式化都会出现这个问题. 我之前做过测试, 不使用这个 Zicron 插件, 格式化代码不会出现这个问题

![image](https://user-images.githubusercontent.com/44739137/188263495-94d1b772-298f-4538-83e0-776570c66bd5.png)
![image](https://user-images.githubusercontent.com/44739137/188263499-357b8574-03f1-4eda-be35-2fa04132e418.png)

**Comment by 122006** [comment]
在过去的版本，已经修复了这个问题，被错误地包裹进了一个空格，感谢，
