### ISSUE TITLE
-Xplugin:ZrExMethod编译参数问题

### ISSUE THREAD

**Issue by pi-dan** [122006/Zircon#8]
大佬，3.1.2版本，maven3.6.3，jdk11，加了编译参数 <arg>-Xplugin:ZrExMethod</arg>后，编译一个springboot项目需要半个多小时，去掉后1分钟内就可以编译完成，用了两台电脑试了都是这个情况

**Comment by 122006** [comment]
已更新3.1.3版本，对编译速度进行了优化。感谢反馈
