### ISSUE TITLE
不支持在build.gradle的plugins块内apply plugin

### ISSUE THREAD

**Issue by vfyjxf** [122006/Zircon#9]
![image](https://github.com/122006/Zircon/assets/42764413/bc42d7e7-cf82-4a58-90d8-2d243c47c7ff)
如图，如果使用这种写法而非README提供的方法，gradle会找不到plugin。
已在settings.gradle内设置了jitpack作为plugin源。

**Comment by 122006** [comment]
感谢使用，3.1.4版本已支持使用id方式引入。
推荐手动选择使用最新的3.1版本idea插件以获得更好的体验哦

**Comment by vfyjxf** [comment]
问一下id是什么，zircon貌似不行（？）

**Comment by 122006** [comment]
> 问一下id是什么，zircon貌似不行（？）

如你之前所写的那样
````
plugins {
    id 'com.android.application'
    id 'zircon'
}
````
请确认已更新插件版本至3.1.4：````classpath 'com.github.122006.Zircon:gradle:3.1.4'````
如果还是不行，麻烦clean下项目再试试。

**Comment by vfyjxf** [comment]
> 请确认已更新插件版本至3.1.4：`classpath 'com.github.122006.Zircon:gradle:3.1.4'` 如果还是不行，麻烦clean下项目再试试。

其实我就是不想在buildscript写classpath这一段，不能把plugin push到某个maven上面吗？
